version: "3.7"

services:
  ghost-svc:
    image: ghost:5.55.2
    restart: always
    depends_on:
      - mysql-service
    ports:
      - 2367:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mysql-service
      database__connection__user: root
      database__connection__password: ${database__connection__password}
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://${VIRTUAL_HOST_NAME}
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: production
      # VIRTUAL_HOST: ${VIRTUAL_HOST_NAME}
      # VIRTUAL_PORT: 2368
    labels:
      # enable traefik
      - "traefik.enable=true"
      # Define routers
      - "traefik.http.routers.${GHOST_ROUTEUR_NAME}.rule=Host(`${GHOST_HOST_NAME}`)"
      - "traefik.http.routers.${GHOST_ROUTEUR_NAME}.entrypoints=websecure"
      # service
      - traefik.http.services.${GHOST_SERVICE_NAME}.loadbalancer.server.port=${GHOST_HOST_PORT}
    networks:
      - default
      - nginx_my-network
      - traefik_my-network
    volumes:
      - ghost-data:/var/lib/ghost/content 
    
  mysql-service:
    image: mysql:8.0.34
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default

networks:
  nginx_my-network:
    external: true
  traefik_my-network:
    external: true

volumes:
  ghost-data:
  mysql-data: