apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-test
  template:
    metadata:
      labels:
        app: flask-test
    spec:
      containers:
        - name: flask-test
          image: diandev/flask-test:v1
          ports:
            - containerPort: 5000
---            
apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
