version: '3'

services:
  grafana-svc:
    image: grafana/grafana:10.2.0
    container_name: grafana
    volumes:
      - ./grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
      - GF_USERS_ALLOW_SIGN_UP=false
      - VIRTUAL_HOST=grafana-saguidorde.com
      - VIRTUAL_PORT=3000
    restart: unless-stopped
    ports:
      - 3033:3000
    networks:
      - monitoring-network
      - default

  prometheus-svc:
    image: prom/prometheus:v2.47.2
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitoring-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  blackbox-svc:
    image: prom/blackbox-exporter
    container_name: blackbox
    ports:
      - "9115:9115"
    volumes:
      - ./prometheus/config.yml:/etc/blackbox_exporter/config.yml
    networks:
      - monitoring-network

  node-exporter-svc:
    image: prom/node-exporter:v1.2.2
    ports:
      - 9191:9100
    networks:
      - monitoring-network

  cadvisor-svc:
    image: wavefronthq/cadvisor:latest
    ports:
      - 8085:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - monitoring-network

volumes:
  prometheus-data:
  
networks:
  monitoring-network:
    external: true