version: '3'

services:
  mysql-db:
    image: mysql:5.7.44
    environment:
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8880:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql-db
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
     - 8888:8080