version: "3.7"
services:
  proxy-svc:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "81:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - my-network

  web-svc:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - my-network

networks:
  my-network:
    external: false