# Spécification du Secret pour les informations d'authentification de Mongo Express
apiVersion: v1
kind: Secret
metadata:
  # Nom du Secret
  name: mongo-secret
# Type Opaque est utilisé pour stocker des données arbitraires
type: Opaque
data:
  # Clé et valeur encodées en base64 pour le nom d'utilisateur d'authentification de base
  basic_auth_username: dXNlcg==
  # Clé et valeur encodées en base64 pour le mot de passe d'authentification de base
  basic_auth_password: bGltYm9jbw==

# Ce fichier YAML définit un Secret nommé "mongo-secret" de type "Opaque"
# (qui peut stocker n'importe quel type de données). 
# Il contient deux paires clé-valeur encodées en base64, représentant le nom d'utilisateur 
# et le mot de passe d'authentification de base utilisés par Mongo Express.